// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSNXuMnlh1YO2FsV9q80-utiUk-_ZdFU',
    appId: '1:1048814642974:web:4e9d382ec3c5e792bdcb0f',
    messagingSenderId: '1048814642974',
    projectId: 'fir-flutter-codelab-7c576',
    authDomain: 'fir-flutter-codelab-7c576.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-7c576.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD27sjZIj-LMyrsg_FoRvy9mv803Jwptjw',
    appId: '1:1048814642974:android:d624e6d6e6fe96cabdcb0f',
    messagingSenderId: '1048814642974',
    projectId: 'fir-flutter-codelab-7c576',
    storageBucket: 'fir-flutter-codelab-7c576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLavIfr2Rls9Mjhe81ZC9VJVVXJr-tOas',
    appId: '1:1048814642974:ios:027c69907d3036a1bdcb0f',
    messagingSenderId: '1048814642974',
    projectId: 'fir-flutter-codelab-7c576',
    storageBucket: 'fir-flutter-codelab-7c576.appspot.com',
    iosClientId: '1048814642974-b5v9mj67a9fnk59jfknts85dgr0vv6j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePart2',
  );
}
